# coding: utf-8

"""
    Valour API

    The official Valour API  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.notifications_api_api import NotificationsAPIApi  # noqa: E501
from swagger_client.rest import ApiException


class TestNotificationsAPIApi(unittest.TestCase):
    """NotificationsAPIApi unit test stubs"""

    def setUp(self):
        self.api = NotificationsAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_notification_subscribe_post(self):
        """Test case for api_notification_subscribe_post

        """
        pass

    def test_api_notification_unsubscribe_post(self):
        """Test case for api_notification_unsubscribe_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
