# coding: utf-8

"""
    Valour API

    The official Valour API  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.proxy_api_api import ProxyApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProxyApiApi(unittest.TestCase):
    """ProxyApiApi unit test stubs"""

    def setUp(self):
        self.api = ProxyApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_proxy_url_get(self):
        """Test case for proxy_url_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
