# coding: utf-8

"""
    Valour API

    The official Valour API  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user_friend_api_api import UserFriendApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserFriendApiApi(unittest.TestCase):
    """UserFriendApiApi unit test stubs"""

    def setUp(self):
        self.api = UserFriendApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_userfriends_add_friend_username_post(self):
        """Test case for api_userfriends_add_friend_username_post

        """
        pass

    def test_api_userfriends_cancel_username_post(self):
        """Test case for api_userfriends_cancel_username_post

        """
        pass

    def test_api_userfriends_decline_username_post(self):
        """Test case for api_userfriends_decline_username_post

        """
        pass

    def test_api_userfriends_remove_friend_username_post(self):
        """Test case for api_userfriends_remove_friend_username_post

        """
        pass

    def test_api_userfriends_user_id_friend_id_get(self):
        """Test case for api_userfriends_user_id_friend_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
