# coding: utf-8

"""
    Valour API

    The official Valour API  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.register_user_request import RegisterUserRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestRegisterUserRequest(unittest.TestCase):
    """RegisterUserRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegisterUserRequest(self):
        """Test RegisterUserRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.register_user_request.RegisterUserRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
