# coding: utf-8

"""
    Valour API

    The official Valour API  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.channel_api_api import ChannelApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestChannelApiApi(unittest.TestCase):
    """ChannelApiApi unit test stubs"""

    def setUp(self):
        self.api = ChannelApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_channels_channel_id_children_get(self):
        """Test case for api_channels_channel_id_children_get

        """
        pass

    def test_api_channels_channel_id_messages_get(self):
        """Test case for api_channels_channel_id_messages_get

        """
        pass

    def test_api_channels_channel_id_messages_message_id_delete(self):
        """Test case for api_channels_channel_id_messages_message_id_delete

        """
        pass

    def test_api_channels_channel_id_messages_message_id_get(self):
        """Test case for api_channels_channel_id_messages_message_id_get

        """
        pass

    def test_api_channels_channel_id_messages_message_id_put(self):
        """Test case for api_channels_channel_id_messages_message_id_put

        """
        pass

    def test_api_channels_channel_id_messages_post(self):
        """Test case for api_channels_channel_id_messages_post

        """
        pass

    def test_api_channels_channel_id_nodes_get(self):
        """Test case for api_channels_channel_id_nodes_get

        """
        pass

    def test_api_channels_channel_id_non_planet_members_get(self):
        """Test case for api_channels_channel_id_non_planet_members_get

        """
        pass

    def test_api_channels_direct_other_user_id_get(self):
        """Test case for api_channels_direct_other_user_id_get

        """
        pass

    def test_api_channels_direct_self_get(self):
        """Test case for api_channels_direct_self_get

        """
        pass

    def test_api_channels_id_get(self):
        """Test case for api_channels_id_get

        """
        pass

    def test_api_channels_id_typing_post(self):
        """Test case for api_channels_id_typing_post

        """
        pass

    def test_api_channels_post(self):
        """Test case for api_channels_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
