# coding: utf-8

"""
    Valour API

    The official Valour API  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.tenor_favorite_api_api import TenorFavoriteApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTenorFavoriteApiApi(unittest.TestCase):
    """TenorFavoriteApiApi unit test stubs"""

    def setUp(self):
        self.api = TenorFavoriteApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_tenorfavorites_id_delete(self):
        """Test case for api_tenorfavorites_id_delete

        """
        pass

    def test_api_tenorfavorites_post(self):
        """Test case for api_tenorfavorites_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
