# coding: utf-8

"""
    Valour API

    The official Valour API  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.planet_member_api_api import PlanetMemberApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPlanetMemberApiApi(unittest.TestCase):
    """PlanetMemberApiApi unit test stubs"""

    def setUp(self):
        self.api = PlanetMemberApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_members_byuser_planet_id_user_id_get(self):
        """Test case for api_members_byuser_planet_id_user_id_get

        """
        pass

    def test_api_members_id_authority_get(self):
        """Test case for api_members_id_authority_get

        """
        pass

    def test_api_members_id_delete(self):
        """Test case for api_members_id_delete

        """
        pass

    def test_api_members_id_get(self):
        """Test case for api_members_id_get

        """
        pass

    def test_api_members_id_put(self):
        """Test case for api_members_id_put

        """
        pass

    def test_api_members_id_roles_get(self):
        """Test case for api_members_id_roles_get

        """
        pass

    def test_api_members_id_roles_role_id_delete(self):
        """Test case for api_members_id_roles_role_id_delete

        """
        pass

    def test_api_members_id_roles_role_id_post(self):
        """Test case for api_members_id_roles_role_id_post

        """
        pass

    def test_api_members_self_planet_id_get(self):
        """Test case for api_members_self_planet_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
