# coding: utf-8

"""
    Valour API

    The official Valour API  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.node_handshake_response import NodeHandshakeResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestNodeHandshakeResponse(unittest.TestCase):
    """NodeHandshakeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNodeHandshakeResponse(self):
        """Test NodeHandshakeResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.node_handshake_response.NodeHandshakeResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
