# coding: utf-8

"""
    Valour API

    The official Valour API  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user_profile_api_api import UserProfileApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserProfileApiApi(unittest.TestCase):
    """UserProfileApiApi unit test stubs"""

    def setUp(self):
        self.api = UserProfileApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_user_profiles_id_get(self):
        """Test case for api_user_profiles_id_get

        """
        pass

    def test_api_user_profiles_id_put(self):
        """Test case for api_user_profiles_id_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
