# coding: utf-8

"""
    Valour API

    The official Valour API  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.eco_api_api import EcoApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEcoApiApi(unittest.TestCase):
    """EcoApiApi unit test stubs"""

    def setUp(self):
        self.api = EcoApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_eco_accounts_byname_username_get(self):
        """Test case for api_eco_accounts_byname_username_get

        """
        pass

    def test_api_eco_accounts_id_delete(self):
        """Test case for api_eco_accounts_id_delete

        """
        pass

    def test_api_eco_accounts_id_get(self):
        """Test case for api_eco_accounts_id_get

        """
        pass

    def test_api_eco_accounts_id_put(self):
        """Test case for api_eco_accounts_id_put

        """
        pass

    def test_api_eco_accounts_planet_can_send_post(self):
        """Test case for api_eco_accounts_planet_can_send_post

        """
        pass

    def test_api_eco_accounts_planet_planet_id_byuser_user_id_get(self):
        """Test case for api_eco_accounts_planet_planet_id_byuser_user_id_get

        """
        pass

    def test_api_eco_accounts_planet_planet_id_member_get(self):
        """Test case for api_eco_accounts_planet_planet_id_member_get

        """
        pass

    def test_api_eco_accounts_planet_planet_id_planet_get(self):
        """Test case for api_eco_accounts_planet_planet_id_planet_get

        """
        pass

    def test_api_eco_accounts_planet_planet_id_user_get(self):
        """Test case for api_eco_accounts_planet_planet_id_user_get

        """
        pass

    def test_api_eco_accounts_post(self):
        """Test case for api_eco_accounts_post

        """
        pass

    def test_api_eco_accounts_self_get(self):
        """Test case for api_eco_accounts_self_get

        """
        pass

    def test_api_eco_accounts_self_global_get(self):
        """Test case for api_eco_accounts_self_global_get

        """
        pass

    def test_api_eco_currencies_by_planet_planet_id_get(self):
        """Test case for api_eco_currencies_by_planet_planet_id_get

        """
        pass

    def test_api_eco_currencies_id_get(self):
        """Test case for api_eco_currencies_id_get

        """
        pass

    def test_api_eco_currencies_id_put(self):
        """Test case for api_eco_currencies_id_put

        """
        pass

    def test_api_eco_currencies_post(self):
        """Test case for api_eco_currencies_post

        """
        pass

    def test_api_eco_transactions_id_get(self):
        """Test case for api_eco_transactions_id_get

        """
        pass

    def test_api_eco_transactions_id_receipt_get(self):
        """Test case for api_eco_transactions_id_receipt_get

        """
        pass

    def test_api_eco_transactions_post(self):
        """Test case for api_eco_transactions_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
