# coding: utf-8

"""
    Valour API

    The official Valour API  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.planet_api_api import PlanetApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPlanetApiApi(unittest.TestCase):
    """PlanetApiApi unit test stubs"""

    def setUp(self):
        self.api = PlanetApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_planets_discoverable_get(self):
        """Test case for api_planets_discoverable_get

        """
        pass

    def test_api_planets_id_categories_get(self):
        """Test case for api_planets_id_categories_get

        """
        pass

    def test_api_planets_id_channels_chat_get(self):
        """Test case for api_planets_id_channels_chat_get

        """
        pass

    def test_api_planets_id_channels_get(self):
        """Test case for api_planets_id_channels_get

        """
        pass

    def test_api_planets_id_channels_voice_get(self):
        """Test case for api_planets_id_channels_voice_get

        """
        pass

    def test_api_planets_id_delete(self):
        """Test case for api_planets_id_delete

        """
        pass

    def test_api_planets_id_discover_post(self):
        """Test case for api_planets_id_discover_post

        """
        pass

    def test_api_planets_id_get(self):
        """Test case for api_planets_id_get

        """
        pass

    def test_api_planets_id_invites_get(self):
        """Test case for api_planets_id_invites_get

        """
        pass

    def test_api_planets_id_invites_ids_get(self):
        """Test case for api_planets_id_invites_ids_get

        """
        pass

    def test_api_planets_id_join_post(self):
        """Test case for api_planets_id_join_post

        """
        pass

    def test_api_planets_id_memberinfo_get(self):
        """Test case for api_planets_id_memberinfo_get

        """
        pass

    def test_api_planets_id_put(self):
        """Test case for api_planets_id_put

        """
        pass

    def test_api_planets_id_roles_get(self):
        """Test case for api_planets_id_roles_get

        """
        pass

    def test_api_planets_id_roles_ids_get(self):
        """Test case for api_planets_id_roles_ids_get

        """
        pass

    def test_api_planets_id_roles_order_post(self):
        """Test case for api_planets_id_roles_order_post

        """
        pass

    def test_api_planets_planet_id_planet_channels_insert_post(self):
        """Test case for api_planets_planet_id_planet_channels_insert_post

        """
        pass

    def test_api_planets_planet_id_planet_channels_order_post(self):
        """Test case for api_planets_planet_id_planet_channels_order_post

        """
        pass

    def test_api_planets_post(self):
        """Test case for api_planets_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
