# coding: utf-8

"""
    Valour API

    The official Valour API  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.notification_api_api import NotificationApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestNotificationApiApi(unittest.TestCase):
    """NotificationApiApi unit test stubs"""

    def setUp(self):
        self.api = NotificationApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_notifications_self_clear_post(self):
        """Test case for api_notifications_self_clear_post

        """
        pass

    def test_api_notifications_self_id_read_value_post(self):
        """Test case for api_notifications_self_id_read_value_post

        """
        pass

    def test_api_notifications_self_unread_all_get(self):
        """Test case for api_notifications_self_unread_all_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
