# coding: utf-8

"""
    Valour API

    The official Valour API  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.subscription_api_api import SubscriptionApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSubscriptionApiApi(unittest.TestCase):
    """SubscriptionApiApi unit test stubs"""

    def setUp(self):
        self.api = SubscriptionApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_subscriptions_active_user_id_get(self):
        """Test case for api_subscriptions_active_user_id_get

        """
        pass

    def test_api_subscriptions_end_post(self):
        """Test case for api_subscriptions_end_post

        """
        pass

    def test_api_subscriptions_sub_type_price_get(self):
        """Test case for api_subscriptions_sub_type_price_get

        """
        pass

    def test_api_subscriptions_sub_type_start_post(self):
        """Test case for api_subscriptions_sub_type_start_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
