# coding: utf-8

"""
    Valour API

    The official Valour API  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.planet_ban_api_api import PlanetBanApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPlanetBanApiApi(unittest.TestCase):
    """PlanetBanApiApi unit test stubs"""

    def setUp(self):
        self.api = PlanetBanApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_bans_id_delete(self):
        """Test case for api_bans_id_delete

        """
        pass

    def test_api_bans_id_get(self):
        """Test case for api_bans_id_get

        """
        pass

    def test_api_bans_id_put(self):
        """Test case for api_bans_id_put

        """
        pass

    def test_api_bans_post(self):
        """Test case for api_bans_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
