# coding: utf-8

"""
    Valour API

    The official Valour API  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.upload_api_api import UploadApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUploadApiApi(unittest.TestCase):
    """UploadApiApi unit test stubs"""

    def setUp(self):
        self.api = UploadApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_upload_app_app_id_post(self):
        """Test case for upload_app_app_id_post

        """
        pass

    def test_upload_file_plus_post(self):
        """Test case for upload_file_plus_post

        """
        pass

    def test_upload_file_post(self):
        """Test case for upload_file_post

        """
        pass

    def test_upload_image_plus_post(self):
        """Test case for upload_image_plus_post

        """
        pass

    def test_upload_image_post(self):
        """Test case for upload_image_post

        """
        pass

    def test_upload_planet_planet_id_post(self):
        """Test case for upload_planet_planet_id_post

        """
        pass

    def test_upload_profile_post(self):
        """Test case for upload_profile_post

        """
        pass

    def test_upload_profilebg_post(self):
        """Test case for upload_profilebg_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
