# coding: utf-8

"""
    Valour API

    The official Valour API  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.planet_ban import PlanetBan  # noqa: E501
from swagger_client.rest import ApiException


class TestPlanetBan(unittest.TestCase):
    """PlanetBan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlanetBan(self):
        """Test PlanetBan"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.planet_ban.PlanetBan()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
