# coding: utf-8

"""
    Valour API

    The official Valour API  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.embed_api_api import EmbedAPIApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEmbedAPIApi(unittest.TestCase):
    """EmbedAPIApi unit test stubs"""

    def setUp(self):
        self.api = EmbedAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_embed_interact_post(self):
        """Test case for api_embed_interact_post

        """
        pass

    def test_api_embed_planetchannelupdate_post(self):
        """Test case for api_embed_planetchannelupdate_post

        """
        pass

    def test_api_embed_planetpersonalupdate_post(self):
        """Test case for api_embed_planetpersonalupdate_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
