# coding: utf-8

"""
    Valour API

    The official Valour API  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.planet_invite_api_api import PlanetInviteApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPlanetInviteApiApi(unittest.TestCase):
    """PlanetInviteApiApi unit test stubs"""

    def setUp(self):
        self.api = PlanetInviteApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_invites_id_delete(self):
        """Test case for api_invites_id_delete

        """
        pass

    def test_api_invites_id_put(self):
        """Test case for api_invites_id_put

        """
        pass

    def test_api_invites_invite_code_get(self):
        """Test case for api_invites_invite_code_get

        """
        pass

    def test_api_invites_invite_code_planeticon_get(self):
        """Test case for api_invites_invite_code_planeticon_get

        """
        pass

    def test_api_invites_invite_code_planetname_get(self):
        """Test case for api_invites_invite_code_planetname_get

        """
        pass

    def test_api_invites_invite_code_screen_get(self):
        """Test case for api_invites_invite_code_screen_get

        """
        pass

    def test_api_invites_post(self):
        """Test case for api_invites_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
