# coding: utf-8

"""
    Valour API

    The official Valour API  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AuthorizeModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'client_id': 'int',
        'redirect_uri': 'str',
        'user_id': 'int',
        'response_type': 'str',
        'scope': 'int',
        'state': 'str',
        'code': 'str'
    }

    attribute_map = {
        'client_id': 'client_id',
        'redirect_uri': 'redirect_uri',
        'user_id': 'userId',
        'response_type': 'response_type',
        'scope': 'scope',
        'state': 'state',
        'code': 'code'
    }

    def __init__(self, client_id=None, redirect_uri=None, user_id=None, response_type=None, scope=None, state=None, code=None):  # noqa: E501
        """AuthorizeModel - a model defined in Swagger"""  # noqa: E501
        self._client_id = None
        self._redirect_uri = None
        self._user_id = None
        self._response_type = None
        self._scope = None
        self._state = None
        self._code = None
        self.discriminator = None
        if client_id is not None:
            self.client_id = client_id
        if redirect_uri is not None:
            self.redirect_uri = redirect_uri
        if user_id is not None:
            self.user_id = user_id
        if response_type is not None:
            self.response_type = response_type
        if scope is not None:
            self.scope = scope
        if state is not None:
            self.state = state
        if code is not None:
            self.code = code

    @property
    def client_id(self):
        """Gets the client_id of this AuthorizeModel.  # noqa: E501


        :return: The client_id of this AuthorizeModel.  # noqa: E501
        :rtype: int
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """Sets the client_id of this AuthorizeModel.


        :param client_id: The client_id of this AuthorizeModel.  # noqa: E501
        :type: int
        """

        self._client_id = client_id

    @property
    def redirect_uri(self):
        """Gets the redirect_uri of this AuthorizeModel.  # noqa: E501


        :return: The redirect_uri of this AuthorizeModel.  # noqa: E501
        :rtype: str
        """
        return self._redirect_uri

    @redirect_uri.setter
    def redirect_uri(self, redirect_uri):
        """Sets the redirect_uri of this AuthorizeModel.


        :param redirect_uri: The redirect_uri of this AuthorizeModel.  # noqa: E501
        :type: str
        """

        self._redirect_uri = redirect_uri

    @property
    def user_id(self):
        """Gets the user_id of this AuthorizeModel.  # noqa: E501


        :return: The user_id of this AuthorizeModel.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this AuthorizeModel.


        :param user_id: The user_id of this AuthorizeModel.  # noqa: E501
        :type: int
        """

        self._user_id = user_id

    @property
    def response_type(self):
        """Gets the response_type of this AuthorizeModel.  # noqa: E501


        :return: The response_type of this AuthorizeModel.  # noqa: E501
        :rtype: str
        """
        return self._response_type

    @response_type.setter
    def response_type(self, response_type):
        """Sets the response_type of this AuthorizeModel.


        :param response_type: The response_type of this AuthorizeModel.  # noqa: E501
        :type: str
        """

        self._response_type = response_type

    @property
    def scope(self):
        """Gets the scope of this AuthorizeModel.  # noqa: E501


        :return: The scope of this AuthorizeModel.  # noqa: E501
        :rtype: int
        """
        return self._scope

    @scope.setter
    def scope(self, scope):
        """Sets the scope of this AuthorizeModel.


        :param scope: The scope of this AuthorizeModel.  # noqa: E501
        :type: int
        """

        self._scope = scope

    @property
    def state(self):
        """Gets the state of this AuthorizeModel.  # noqa: E501


        :return: The state of this AuthorizeModel.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this AuthorizeModel.


        :param state: The state of this AuthorizeModel.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def code(self):
        """Gets the code of this AuthorizeModel.  # noqa: E501


        :return: The code of this AuthorizeModel.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this AuthorizeModel.


        :param code: The code of this AuthorizeModel.  # noqa: E501
        :type: str
        """

        self._code = code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AuthorizeModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuthorizeModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
