# coding: utf-8

"""
    Valour API

    The official Valour API  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EcoPlanetAccountSearchRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'planet_id': 'int',
        'account_id': 'int',
        'filter': 'str'
    }

    attribute_map = {
        'planet_id': 'planetId',
        'account_id': 'accountId',
        'filter': 'filter'
    }

    def __init__(self, planet_id=None, account_id=None, filter=None):  # noqa: E501
        """EcoPlanetAccountSearchRequest - a model defined in Swagger"""  # noqa: E501
        self._planet_id = None
        self._account_id = None
        self._filter = None
        self.discriminator = None
        if planet_id is not None:
            self.planet_id = planet_id
        if account_id is not None:
            self.account_id = account_id
        if filter is not None:
            self.filter = filter

    @property
    def planet_id(self):
        """Gets the planet_id of this EcoPlanetAccountSearchRequest.  # noqa: E501


        :return: The planet_id of this EcoPlanetAccountSearchRequest.  # noqa: E501
        :rtype: int
        """
        return self._planet_id

    @planet_id.setter
    def planet_id(self, planet_id):
        """Sets the planet_id of this EcoPlanetAccountSearchRequest.


        :param planet_id: The planet_id of this EcoPlanetAccountSearchRequest.  # noqa: E501
        :type: int
        """

        self._planet_id = planet_id

    @property
    def account_id(self):
        """Gets the account_id of this EcoPlanetAccountSearchRequest.  # noqa: E501


        :return: The account_id of this EcoPlanetAccountSearchRequest.  # noqa: E501
        :rtype: int
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """Sets the account_id of this EcoPlanetAccountSearchRequest.


        :param account_id: The account_id of this EcoPlanetAccountSearchRequest.  # noqa: E501
        :type: int
        """

        self._account_id = account_id

    @property
    def filter(self):
        """Gets the filter of this EcoPlanetAccountSearchRequest.  # noqa: E501


        :return: The filter of this EcoPlanetAccountSearchRequest.  # noqa: E501
        :rtype: str
        """
        return self._filter

    @filter.setter
    def filter(self, filter):
        """Sets the filter of this EcoPlanetAccountSearchRequest.


        :param filter: The filter of this EcoPlanetAccountSearchRequest.  # noqa: E501
        :type: str
        """

        self._filter = filter

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EcoPlanetAccountSearchRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EcoPlanetAccountSearchRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
