# coding: utf-8

"""
    Valour API

    The official Valour API  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class PlanetInviteApiApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def api_invites_id_delete(self, id, **kwargs):  # noqa: E501
        """api_invites_id_delete  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_invites_id_delete(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.api_invites_id_delete_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.api_invites_id_delete_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def api_invites_id_delete_with_http_info(self, id, **kwargs):  # noqa: E501
        """api_invites_id_delete  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_invites_id_delete_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_invites_id_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `api_invites_id_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/invites/{id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def api_invites_id_put(self, **kwargs):  # noqa: E501
        """api_invites_id_put  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_invites_id_put(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PlanetInvite body:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.api_invites_id_put_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.api_invites_id_put_with_http_info(**kwargs)  # noqa: E501
            return data

    def api_invites_id_put_with_http_info(self, **kwargs):  # noqa: E501
        """api_invites_id_put  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_invites_id_put_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PlanetInvite body:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_invites_id_put" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/invites/{id}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def api_invites_invite_code_get(self, invite_code, **kwargs):  # noqa: E501
        """api_invites_invite_code_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_invites_invite_code_get(invite_code, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str invite_code: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.api_invites_invite_code_get_with_http_info(invite_code, **kwargs)  # noqa: E501
        else:
            (data) = self.api_invites_invite_code_get_with_http_info(invite_code, **kwargs)  # noqa: E501
            return data

    def api_invites_invite_code_get_with_http_info(self, invite_code, **kwargs):  # noqa: E501
        """api_invites_invite_code_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_invites_invite_code_get_with_http_info(invite_code, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str invite_code: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['invite_code']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_invites_invite_code_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'invite_code' is set
        if ('invite_code' not in params or
                params['invite_code'] is None):
            raise ValueError("Missing the required parameter `invite_code` when calling `api_invites_invite_code_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'invite_code' in params:
            path_params['inviteCode'] = params['invite_code']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/invites/{inviteCode}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def api_invites_invite_code_planeticon_get(self, invite_code, **kwargs):  # noqa: E501
        """api_invites_invite_code_planeticon_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_invites_invite_code_planeticon_get(invite_code, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str invite_code: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.api_invites_invite_code_planeticon_get_with_http_info(invite_code, **kwargs)  # noqa: E501
        else:
            (data) = self.api_invites_invite_code_planeticon_get_with_http_info(invite_code, **kwargs)  # noqa: E501
            return data

    def api_invites_invite_code_planeticon_get_with_http_info(self, invite_code, **kwargs):  # noqa: E501
        """api_invites_invite_code_planeticon_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_invites_invite_code_planeticon_get_with_http_info(invite_code, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str invite_code: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['invite_code']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_invites_invite_code_planeticon_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'invite_code' is set
        if ('invite_code' not in params or
                params['invite_code'] is None):
            raise ValueError("Missing the required parameter `invite_code` when calling `api_invites_invite_code_planeticon_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'invite_code' in params:
            path_params['inviteCode'] = params['invite_code']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/invites/{inviteCode}/planeticon', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def api_invites_invite_code_planetname_get(self, invite_code, **kwargs):  # noqa: E501
        """api_invites_invite_code_planetname_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_invites_invite_code_planetname_get(invite_code, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str invite_code: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.api_invites_invite_code_planetname_get_with_http_info(invite_code, **kwargs)  # noqa: E501
        else:
            (data) = self.api_invites_invite_code_planetname_get_with_http_info(invite_code, **kwargs)  # noqa: E501
            return data

    def api_invites_invite_code_planetname_get_with_http_info(self, invite_code, **kwargs):  # noqa: E501
        """api_invites_invite_code_planetname_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_invites_invite_code_planetname_get_with_http_info(invite_code, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str invite_code: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['invite_code']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_invites_invite_code_planetname_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'invite_code' is set
        if ('invite_code' not in params or
                params['invite_code'] is None):
            raise ValueError("Missing the required parameter `invite_code` when calling `api_invites_invite_code_planetname_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'invite_code' in params:
            path_params['inviteCode'] = params['invite_code']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/invites/{inviteCode}/planetname', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def api_invites_invite_code_screen_get(self, invite_code, **kwargs):  # noqa: E501
        """api_invites_invite_code_screen_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_invites_invite_code_screen_get(invite_code, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str invite_code: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.api_invites_invite_code_screen_get_with_http_info(invite_code, **kwargs)  # noqa: E501
        else:
            (data) = self.api_invites_invite_code_screen_get_with_http_info(invite_code, **kwargs)  # noqa: E501
            return data

    def api_invites_invite_code_screen_get_with_http_info(self, invite_code, **kwargs):  # noqa: E501
        """api_invites_invite_code_screen_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_invites_invite_code_screen_get_with_http_info(invite_code, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str invite_code: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['invite_code']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_invites_invite_code_screen_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'invite_code' is set
        if ('invite_code' not in params or
                params['invite_code'] is None):
            raise ValueError("Missing the required parameter `invite_code` when calling `api_invites_invite_code_screen_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'invite_code' in params:
            path_params['inviteCode'] = params['invite_code']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/invites/{inviteCode}/screen', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def api_invites_post(self, **kwargs):  # noqa: E501
        """api_invites_post  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_invites_post(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PlanetInvite body:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.api_invites_post_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.api_invites_post_with_http_info(**kwargs)  # noqa: E501
            return data

    def api_invites_post_with_http_info(self, **kwargs):  # noqa: E501
        """api_invites_post  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_invites_post_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PlanetInvite body:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_invites_post" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/invites', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
